version: 2
jobs:
  build:
    working_directory: ~/Android/Workspace/SocialMediaHelper

    docker:
      - image: circleci/android:api-25-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - script:
          - ./gradlew lint test
          - ./gradlew pmd test
          - ./gradlew findBugs test
          - ./gradlew build jacocoTestReport assembleAndroidTest
          - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
          - emulator -avd test -no-skin -no-audio -no-window &
          - android-wait-for-emulator
          - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
          - ./gradlew connectedCheck
      after_success:
          - bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: library/build/reports/
          destination: reports
      - store_test_results:
          path: library/build/reports/test_results